language: generic
os: linux
dist: xenial
services:
  - docker

before_install:
  - docker build -t korkhan/client-test -f test ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true korkhan/client-test npm run test

after_success:
  - docker build -t korkhan/multi-client ./client
  - docker build -t korkhan/multi-nginx ./nginx
  - docker build -t korkhan/multi-server ./server
  - docker build -t korkhan/multi-worker ./worker
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push korkhan/multi-client
  - docker push korkhan/multi-nginx
  - docker push korkhan/multi-server
  - docker push korkhan/multi-worker
