FROM node:14.14.0-alpine

USER node

RUN mkdir -p /home/node/server
WORKDIR '/home/node/server'

COPY --chown=node:node ./package.json ./
RUN npm install

COPY --chown=node:node ./ ./

CMD ["npm", "run", "dev"]
